### ISSUE TITLE
希望增加Foreign和Domestic的配置都能加上是否返回IPV6选项

### ISSUE THREAD

**Issue by lcylgs** [dnomd343/ClearDNS#2]
希望增加Foreign和Domestic的配置都能加上是否返回IPV6选项
特别是Foreign需要，因为很多时候返回IPV6地址还是会造成无法访问。
不少代理是不支持IPV6的

**Comment by dnomd343** [comment]
可以的，后续会加上这个功能

**Comment by dnomd343** [comment]
目前最新版已经支持 IPv6 禁用选项，请拉取 latest 版本，配置文件的 `foreign` 部分添加 `ipv6: false` 即可屏蔽 Foreign 组的 IPv6 请求（该选项默认为 `true`），返回空解析数据。

示例如下：

```yaml
···
domestic:
  port: xxx
  ipv6: true
···
foreign:
  port: xxx
  ipv6: false
···
```
