### ISSUE TITLE
希望assets里的三个清单能增加本地自定义文件可以合并到最终的list

### ISSUE THREAD

**Issue by lcylgs** [dnomd343/ClearDNS#3]
针对gfwlist.txt，china-ip.txt，chinalist.txt这三个文件希望可以在配置里增加定义本地文件，合并到最终的list里。
这样既可以自己手动增加一些记录（有些网址或者ip段自己非常确认是需要走国内解析的），又能定时更新在线的。
相当于额外增加本地文件作为一个源。
同时可以考虑配置assets的时候支持多个远程源。

**Comment by dnomd343** [comment]
目前可以先在 `diverter` 项中添加指定记录，内容将被合并到最终 list 中，格式如下：

```yaml
diverter:
  port: 5353
  gfwlist: []
  china_ip: []
  chinalist: []
```

本地文件支持、多个远程资源等功能将会在后续版本加入。

**Comment by dnomd343** [comment]
最新版本已经完整支持本地文件、多文件合并功能，示例配置如下：

> 资源文件 value 值可以指定为字符串或者字符串数组，兼容原版配置。

```yaml
assets:
  disable: false
  cron: "0 4 * * *"
  update:
    gfwlist.txt: https://res.dnomd343.top/Share/cleardns/gfwlist.txt
    china-ip.txt: https://res.dnomd343.top/Share/cleardns/china-ip.txt
    chinalist.txt:
      - https://res.dnomd343.top/Share/cleardns/chinalist.txt
      - /tmp/chinalist-local.txt
      - demo.list  # aka `${WorkDir}/assets/demo.list`
    custom.txt:
      - https://.../my-custom-asset.txt
```

资源文件有多个来源时，将自动获取并进行去重合并，如果其中一项读取错误（下载失败或者本地文件不存在），均会导致该资源文件升级失败。

本地文件支持相对路径，例如 ClearDNS 的部署目录为 `/etc/cleardns/` ，则默认资源文件目录为 `/etc/cleardns/assets/` ，您可以将例如 `custom.txt` 的自定义文件放在这个目录中（`/etc/cleardns/assets/custom.txt`），在配置文件内直接使用 `custom.txt` 即可，无需指定绝对路径。
